legacy_textures = [
  # legacy
  'build/blocks/auto_crafter.legacy/back.png',
  'build/blocks/auto_crafter.legacy/bottom.png',
  'build/blocks/auto_crafter.legacy/front.off.png',
  'build/blocks/auto_crafter.legacy/front.on.png',
  'build/blocks/auto_crafter.legacy/side.png',
  'build/blocks/auto_crafter.legacy/top.off.png',
  'build/blocks/auto_crafter.legacy/top.on.png',

  'build/blocks/auto_grinder.legacy/back.png',
  'build/blocks/auto_grinder.legacy/bottom.png',
  'build/blocks/auto_grinder.legacy/front.off.png',
  'build/blocks/auto_grinder.legacy/front.on.png',
  'build/blocks/auto_grinder.legacy/side.png',
  'build/blocks/auto_grinder.legacy/top.off.png',
  'build/blocks/auto_grinder.legacy/top.on.png',

  'build/blocks/coal_generator.legacy/bottom.png',
  'build/blocks/coal_generator.legacy/front.off.png',
  'build/blocks/coal_generator.legacy/front.on.png',
  'build/blocks/coal_generator.legacy/side.png',
  'build/blocks/coal_generator.legacy/top.png',

  'build/blocks/compactor.legacy/back.png',
  'build/blocks/compactor.legacy/bottom.png',
  'build/blocks/compactor.legacy/front.off.png',
  'build/blocks/compactor.legacy/front.on.png',
  'build/blocks/compactor.legacy/side.png',
  'build/blocks/compactor.legacy/top.off.png',
  'build/blocks/compactor.legacy/top.on.png',

  'build/blocks/crusher.legacy/back.png',
  'build/blocks/crusher.legacy/bottom.png',
  'build/blocks/crusher.legacy/front.off.png',
  'build/blocks/crusher.legacy/front.on.png',
  'build/blocks/crusher.legacy/side.png',
  'build/blocks/crusher.legacy/top.off.png',
  'build/blocks/crusher.legacy/top.on.png',

  'build/blocks/flux_furnace.legacy/back.png',
  'build/blocks/flux_furnace.legacy/bottom.png',
  'build/blocks/flux_furnace.legacy/front.off.png',
  'build/blocks/flux_furnace.legacy/front.on.png',
  'build/blocks/flux_furnace.legacy/side.png',
  'build/blocks/flux_furnace.legacy/top.off.png',
  'build/blocks/flux_furnace.legacy/top.on.png',

  'build/blocks/heater.legacy/back.png',
  'build/blocks/heater.legacy/bottom.png',
  'build/blocks/heater.legacy/front.off.png',
  'build/blocks/heater.legacy/front.on.png',
  'build/blocks/heater.legacy/side.png',
  'build/blocks/heater.legacy/top.off.png',
  'build/blocks/heater.legacy/top.on.png',

  'build/blocks/mixer.legacy/back.png',
  'build/blocks/mixer.legacy/bottom.png',
  'build/blocks/mixer.legacy/front.off.png',
  'build/blocks/mixer.legacy/front.on.png',
  'build/blocks/mixer.legacy/side.png',
  'build/blocks/mixer.legacy/top.off.png',
  'build/blocks/mixer.legacy/top.on.png',

  'build/blocks/roller.legacy/back.png',
  'build/blocks/roller.legacy/bottom.png',
  'build/blocks/roller.legacy/front.off.png',
  'build/blocks/roller.legacy/front.on.png',
  'build/blocks/roller.legacy/side.png',
  'build/blocks/roller.legacy/top.off.png',
  'build/blocks/roller.legacy/top.on.png',

  'build/blocks/rfswitch/front.poff.png',
  'build/blocks/rfswitch/front.pon.png',
  'build/blocks/rfswitch/front.uoff.png',
  'build/blocks/rfswitch/front.uon.png',
  'build/blocks/rfswitch/side.poff.png',
  'build/blocks/rfswitch/side.pon.png',
  'build/blocks/rfswitch/side.uoff.png',
  'build/blocks/rfswitch/side.uon.png',
]

tilemaps = [
  *from_tiles("build/tiles/small_cable.t4x4"),
  *from_tiles("build/tiles/small_cable.t4x4"),
  *from_tiles("build/tiles/medium_cable.off.t4x4"),
  *from_tiles("build/tiles/medium_cable.signal.t4x4"),
  *from_tiles("build/tiles/medium_cable.idle.t4x4"),
  *from_tiles("build/tiles/medium_cable.on.t4x4"),
  *from_tiles("build/tiles/dense_cable.off.t4x4"),
  *from_tiles("build/tiles/dense_cable.signal.t4x4"),
  *from_tiles("build/tiles/dense_cable.idle.t4x4"),
  *from_tiles("build/tiles/dense_cable.on.t4x4"),
  #*from_tiles("build/tiles/dense_cable.mask.t4x4"),
  #*from_tiles("build/tiles/riveted_panel.mask.t4x4"),
  *from_tiles("build/tiles/riveted_panel.off.t4x3"),
  *from_tiles("build/tiles/riveted_panel.idle.t4x3"),
  *from_tiles("build/tiles/riveted_panel.signal.t4x3"),
  *from_tiles("build/tiles/riveted_panel.on.t4x3"),
  *from_tiles("build/tiles/floor_panels1.t3x3"),
  *from_tiles("build/tiles/floor_panels2.t3x3"),
  *from_tiles("build/tiles/floor_warning0.t4x3"),
  *from_tiles("build/tiles/floor_warning1.t4x3"),
  *from_tiles("build/tiles/engraved_floor0.t4x3"),
  *from_tiles("build/tiles/engraved_floor1.t4x3"),
  *from_tiles("build/tiles/engraved_floor2.t4x3"),
  *from_tiles("build/tiles/engraved_floor3.t4x3"),
  *from_tiles("build/tiles/engraved_floor4.t4x3"),
  *from_tiles("build/tiles/engraved_floor5.t4x3"),
  *from_tiles("build/tiles/engraved_floor6.t4x3"),
  *from_tiles("build/tiles/engraved_floor7.t4x3"),
  *from_tiles("build/tiles/warning_cells_16x_white.t3x3"),
  *from_tiles("build/tiles/warning_cells_16x_red.t3x3"),
  *from_tiles("build/tiles/warning_cells_16x_yellow.t3x3"),
  *from_tiles("build/tiles/warning_stripes_2x_white.t3x3"),
  *from_tiles("build/tiles/warning_stripes_2x_red.t3x3"),
  *from_tiles("build/tiles/warning_stripes_2x_yellow.t3x3"),
  *from_tiles("build/tiles/warning_stripes_4x_white.t3x3"),
  *from_tiles("build/tiles/warning_stripes_4x_red.t3x3"),
  *from_tiles("build/tiles/warning_stripes_4x_yellow.t3x3"),
  *from_tiles("build/tiles/warning_stripes_8x_white.t3x3"),
  *from_tiles("build/tiles/warning_stripes_8x_red.t3x3"),
  *from_tiles("build/tiles/warning_stripes_8x_yellow.t3x3"),
  *from_tiles("build/tiles/warning_checkers_8x_white.t3x3"),
  *from_tiles("build/tiles/warning_checkers_8x_red.t3x3"),
  *from_tiles("build/tiles/warning_checkers_8x_yellow.t3x3"),
]
sources = [
  #*legacy_textures,
  *tilemaps,
  # new
  'build/blocks/auto_crafter/back.png',
  'build/blocks/auto_crafter/bottom.png',
  'build/blocks/auto_crafter/front.off.png',
  'build/blocks/auto_crafter/front.on.png',
  'build/blocks/auto_crafter/side.png',
  'build/blocks/auto_crafter/top.off.png',
  'build/blocks/auto_crafter/top.on.png',

  'build/blocks/auto_grinder/back.png',
  'build/blocks/auto_grinder/bottom.png',
  'build/blocks/auto_grinder/front.off.png',
  'build/blocks/auto_grinder/front.on.png',
  'build/blocks/auto_grinder/side.png',
  'build/blocks/auto_grinder/top.error.png',
  'build/blocks/auto_grinder/top.idle.png',
  'build/blocks/auto_grinder/top.off.png',
  'build/blocks/auto_grinder/top.on.png',

  'build/blocks/battery_bank/back.level.0.png',
  'build/blocks/battery_bank/back.level.1.png',
  'build/blocks/battery_bank/back.level.2.png',
  'build/blocks/battery_bank/back.level.3.png',
  'build/blocks/battery_bank/back.level.4.png',
  'build/blocks/battery_bank/bottom.png',
  'build/blocks/battery_bank/front.level.0.png',
  'build/blocks/battery_bank/front.level.1.png',
  'build/blocks/battery_bank/front.level.2.png',
  'build/blocks/battery_bank/front.level.3.png',
  'build/blocks/battery_bank/front.level.4.png',
  'build/blocks/battery_bank/side.png',
  'build/blocks/battery_bank/top.off.png',
  'build/blocks/battery_bank/top.on.png',

  'build/blocks/coal_generator/bottom.png',
  'build/blocks/coal_generator/front.off.png',
  'build/blocks/coal_generator/front.on.png',
  'build/blocks/coal_generator/side.png',
  'build/blocks/coal_generator/top.off.png',
  'build/blocks/coal_generator/top.on.png',

  'build/blocks/compactor/back.png',
  'build/blocks/compactor/bottom.png',
  'build/blocks/compactor/front.off.png',
  'build/blocks/compactor/front.on.png',
  'build/blocks/compactor/side.png',
  'build/blocks/compactor/top.off.png',
  'build/blocks/compactor/top.on.png',

  'build/blocks/crusher/back.png',
  'build/blocks/crusher/bottom.png',
  'build/blocks/crusher/front.off.png',
  'build/blocks/crusher/front.on.png',
  'build/blocks/crusher/side.off.png',
  'build/blocks/crusher/side.on.png',
  'build/blocks/crusher/top.off.png',
  'build/blocks/crusher/top.on.png',

  'build/blocks/crystal_cauldron/bottom.png',
  'build/blocks/crystal_cauldron/side.off.png',
  'build/blocks/crystal_cauldron/side.on.png',
  'build/blocks/crystal_cauldron/top.png',

  'build/blocks/drive_case/back.off.png',
  'build/blocks/drive_case/back.on.png',
  'build/blocks/drive_case/bottom.png',
  'build/blocks/drive_case/front.off.png',
  'build/blocks/drive_case/front.on.png',
  'build/blocks/drive_case/side.off.png',
  'build/blocks/drive_case/side.on.png',
  'build/blocks/drive_case/top.png',

  'build/blocks/electrolyser/back.png',
  'build/blocks/electrolyser/bottom.png',
  'build/blocks/electrolyser/front.off.png',
  'build/blocks/electrolyser/front.on.png',
  'build/blocks/electrolyser/side.off.png',
  'build/blocks/electrolyser/side.on.png',
  'build/blocks/electrolyser/top.off.png',
  'build/blocks/electrolyser/top.on.png',

  'build/blocks/energy_cell_basic/creative.png',
  'build/blocks/energy_cell_basic/stage0.png',
  'build/blocks/energy_cell_basic/stage1.png',
  'build/blocks/energy_cell_basic/stage2.png',
  'build/blocks/energy_cell_basic/stage3.png',
  'build/blocks/energy_cell_basic/stage4.png',
  'build/blocks/energy_cell_basic/stage5.png',
  'build/blocks/energy_cell_basic/stage6.png',
  'build/blocks/energy_cell_basic/stage7.png',

  'build/blocks/energy_cell_normal/creative.png',
  'build/blocks/energy_cell_normal/stage0.png',
  'build/blocks/energy_cell_normal/stage1.png',
  'build/blocks/energy_cell_normal/stage2.png',
  'build/blocks/energy_cell_normal/stage3.png',
  'build/blocks/energy_cell_normal/stage4.png',
  'build/blocks/energy_cell_normal/stage5.png',
  'build/blocks/energy_cell_normal/stage6.png',
  'build/blocks/energy_cell_normal/stage7.png',

  'build/blocks/energy_cell_dense/creative.png',
  'build/blocks/energy_cell_dense/stage0.png',
  'build/blocks/energy_cell_dense/stage1.png',
  'build/blocks/energy_cell_dense/stage2.png',
  'build/blocks/energy_cell_dense/stage3.png',
  'build/blocks/energy_cell_dense/stage4.png',
  'build/blocks/energy_cell_dense/stage5.png',
  'build/blocks/energy_cell_dense/stage6.png',
  'build/blocks/energy_cell_dense/stage7.png',

  'build/blocks/fluid_replicator/back.error.png',
  'build/blocks/fluid_replicator/back.idle.png',
  'build/blocks/fluid_replicator/back.off.png',
  'build/blocks/fluid_replicator/back.on.png',
  'build/blocks/fluid_replicator/bottom.png',
  'build/blocks/fluid_replicator/front.error.png',
  'build/blocks/fluid_replicator/front.idle.png',
  'build/blocks/fluid_replicator/front.off.png',
  'build/blocks/fluid_replicator/front.on.png',
  'build/blocks/fluid_replicator/side.error.png',
  'build/blocks/fluid_replicator/side.idle.png',
  'build/blocks/fluid_replicator/side.off.png',
  'build/blocks/fluid_replicator/side.on.png',
  'build/blocks/fluid_replicator/top.error.png',
  'build/blocks/fluid_replicator/top.idle.png',
  'build/blocks/fluid_replicator/top.off.png',
  'build/blocks/fluid_replicator/top.on.png',

  'build/blocks/flux_furnace/back.png',
  'build/blocks/flux_furnace/bottom.png',
  'build/blocks/flux_furnace/front.off.png',
  'build/blocks/flux_furnace/front.on.png',
  'build/blocks/flux_furnace/side.off.png',
  'build/blocks/flux_furnace/side.on.png',
  'build/blocks/flux_furnace/top.off.png',
  'build/blocks/flux_furnace/top.on.png',

  'build/blocks/heater/back.off.png',
  'build/blocks/heater/back.on.png',
  'build/blocks/heater/bottom.png',
  'build/blocks/heater/front.off.png',
  'build/blocks/heater/front.on.png',
  'build/blocks/heater/side.off.png',
  'build/blocks/heater/side.on.png',
  'build/blocks/heater/top.off.png',
  'build/blocks/heater/top.on.png',

  'build/blocks/hub/bottom.png',
  'build/blocks/hub/side.off.png',
  'build/blocks/hub/side.error.png',
  'build/blocks/hub/side.on.png',
  'build/blocks/hub/top.ele.off.png',
  'build/blocks/hub/top.ele.error.png',
  'build/blocks/hub/top.ele.on.png',
  'build/blocks/hub/top.off.png',
  'build/blocks/hub/top.error.png',
  'build/blocks/hub/top.on.png',
  'build/blocks/hub/top.wireless.off.png',
  'build/blocks/hub/top.wireless.error.png',
  'build/blocks/hub/top.wireless.on.png',

  'build/blocks/item_replicator/back.error.png',
  'build/blocks/item_replicator/back.idle.png',
  'build/blocks/item_replicator/back.off.png',
  'build/blocks/item_replicator/back.on.png',
  'build/blocks/item_replicator/bottom.png',
  'build/blocks/item_replicator/front.error.png',
  'build/blocks/item_replicator/front.idle.png',
  'build/blocks/item_replicator/front.off.png',
  'build/blocks/item_replicator/front.on.png',
  'build/blocks/item_replicator/side.error.png',
  'build/blocks/item_replicator/side.idle.png',
  'build/blocks/item_replicator/side.off.png',
  'build/blocks/item_replicator/side.on.png',
  'build/blocks/item_replicator/top.error.png',
  'build/blocks/item_replicator/top.idle.png',
  'build/blocks/item_replicator/top.off.png',
  'build/blocks/item_replicator/top.on.png',

  'build/blocks/jukebox/back.off.png',
  'build/blocks/jukebox/back.on.png',
  'build/blocks/jukebox/bottom.png',
  'build/blocks/jukebox/east.off.png',
  'build/blocks/jukebox/east.on.png',
  'build/blocks/jukebox/west.off.png',
  'build/blocks/jukebox/west.on.png',
  'build/blocks/jukebox/front.off.png',
  'build/blocks/jukebox/front.on.png',
  'build/blocks/jukebox/top.off.png',
  'build/blocks/jukebox/top.on.png',

  'build/blocks/lamp/bottom.off.png',
  'build/blocks/lamp/bottom.on.png',
  'build/blocks/lamp/side.off.png',
  'build/blocks/lamp/side.on.png',
  'build/blocks/lamp/top.off.png',
  'build/blocks/lamp/top.on.png',

  'build/blocks/mixer/back.png',
  'build/blocks/mixer/bottom.png',
  'build/blocks/mixer/front.off.png',
  'build/blocks/mixer/front.on.png',
  'build/blocks/mixer/side.off.png',
  'build/blocks/mixer/side.on.png',
  'build/blocks/mixer/top.off.png',
  'build/blocks/mixer/top.on.png',

  'build/blocks/monitor/back.png',
  'build/blocks/monitor/bottom.png',
  'build/blocks/monitor/front.console.off.png',
  'build/blocks/monitor/front.console.error.png',
  'build/blocks/monitor/front.console.on.png',
  'build/blocks/monitor/front.crafting.off.png',
  'build/blocks/monitor/front.crafting.error.png',
  'build/blocks/monitor/front.crafting.on.png',
  'build/blocks/monitor/front.ele.off.png',
  'build/blocks/monitor/front.ele.error.png',
  'build/blocks/monitor/front.ele.on.png',
  'build/blocks/monitor/front.inventory.off.png',
  'build/blocks/monitor/front.inventory.error.png',
  'build/blocks/monitor/front.inventory.on.png',
  'build/blocks/monitor/side.png',
  'build/blocks/monitor/top.png',

  'build/blocks/pylon/bottom.off.png',
  'build/blocks/pylon/bottom.on.png',
  'build/blocks/pylon/side.off.png',
  'build/blocks/pylon/side.on.png',
  'build/blocks/pylon/top.off.png',
  'build/blocks/pylon/top.on.png',

  'build/blocks/roller/back.png',
  'build/blocks/roller/bottom.png',
  'build/blocks/roller/front.off.png',
  'build/blocks/roller/front.on.png',
  'build/blocks/roller/side.off.png',
  'build/blocks/roller/side.on.png',
  'build/blocks/roller/top.off.png',
  'build/blocks/roller/top.on.png',

  'build/blocks/server/back.off.png',
  'build/blocks/server/back.on.png',
  'build/blocks/server/bottom.png',
  'build/blocks/server/front.off.png',
  'build/blocks/server/front.on.png',
  'build/blocks/server/side.png',
  'build/blocks/server/top.png',

  'build/blocks/server_rack/back.error.png',
  'build/blocks/server_rack/back.off.png',
  'build/blocks/server_rack/back.on.png',
  'build/blocks/server_rack/bottom.png',
  'build/blocks/server_rack/front.error.png',
  'build/blocks/server_rack/front.off.png',
  'build/blocks/server_rack/front.on.png',
  'build/blocks/server_rack/side.error.png',
  'build/blocks/server_rack/side.off.png',
  'build/blocks/server_rack/side.on.png',
  'build/blocks/server_rack/top.png',

  'build/blocks/spring_wound_crank/bottom.off.png',
  'build/blocks/spring_wound_crank/bottom.on.png',
  'build/blocks/spring_wound_crank/bottom.warn.png',
  'build/blocks/spring_wound_crank/side.off.png',
  'build/blocks/spring_wound_crank/side.on.png',
  'build/blocks/spring_wound_crank/side.warn.png',
  'build/blocks/spring_wound_crank/top.off.png',
  'build/blocks/spring_wound_crank/top.on.png',
  'build/blocks/spring_wound_crank/top.warn.png',

  'build/blocks/void_crate/back.off.png',
  'build/blocks/void_crate/back.on.png',
  'build/blocks/void_crate/front.off.png',
  'build/blocks/void_crate/front.on.png',
  'build/blocks/void_crate/side.off.png',
  'build/blocks/void_crate/side.on.png',
  'build/blocks/void_crate/top.off.png',
  'build/blocks/void_crate/top.on.png',

  'build/blocks/wireless_emitter/back.off.png',
  'build/blocks/wireless_emitter/back.on.png',
  'build/blocks/wireless_emitter/bottom.png',
  'build/blocks/wireless_emitter/front.off.png',
  'build/blocks/wireless_emitter/front.on.banding.png',
  'build/blocks/wireless_emitter/front.on.png',
  'build/blocks/wireless_emitter/side.off.png',
  'build/blocks/wireless_emitter/side.on.png',
  'build/blocks/wireless_emitter/top.off.png',
  'build/blocks/wireless_emitter/top.on.png',

  'build/blocks/wireless_receiver/back.off.png',
  'build/blocks/wireless_receiver/back.on.png',
  'build/blocks/wireless_receiver/bottom.png',
  'build/blocks/wireless_receiver/front.off.png',
  'build/blocks/wireless_receiver/front.on.png',
  'build/blocks/wireless_receiver/side.off.png',
  'build/blocks/wireless_receiver/side.on.png',
  'build/blocks/wireless_receiver/top.off.png',
  'build/blocks/wireless_receiver/top.on.png',
]
